version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/git/personal/postgress/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=test_user
      - POSTGRES_DB=test_db
